export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';   
export const LOGIN_FAILURE = 'LOGIN_FAILURE';   
export const LOGOUT = 'LOGOUT';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const CREATE_BOOK_REQUEST = 'CREATE_BOOK_REQUEST';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS'; 
export const CREATE_BOOK_FAILURE = 'CREATE_BOOK_FAILURE'; 

export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST'; 
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS'; 
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';

export const READ_BOOKS_INDEX_REQUEST = 'GET_BOOKS_INDEX_REQUEST';
export const READ_BOOKS_INDEX_SUCCESS = 'GET_BOOKS_INDEX_SUCCESS';
export const READ_BOOKS_INDEX_FAILURE = 'GET_BOOKS_INDEX_FAILURE'; 

export const READ_BOOK_REQUEST = 'READ_BOOK_REQUEST';
export const READ_BOOK_SUCCESS = 'READ_BOOK_SUCCESS';
export const READ_BOOK_FAILURE = 'READ_BOOK_FAILURE'; 

export const UPLOAD_SCAN_REQUEST = 'UPLOAD_SCAN_REQUEST';
export const UPLOAD_SCAN_SUCCESS = 'UPLOAD_SCAN_SUCCESS';
export const UPLOAD_SCAN_FAILURE = 'UPLOAD_SCAN_FAILURE';

export const START_FLOW = 'START_FLOW'; 
export const UPDATE_FLOW = 'UPDATE_FLOW';
export const CLEAN_FLOW = 'CLEAN_FLOW';


