export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';   
export const LOGIN_FAILURE = 'LOGIN_FAILURE';   
export const LOGOUT = 'LOGOUT';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'; 
export const CREATE_NOTE_FAILURE = 'CREATE_NOTE_FAILURE'; 
export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST'; 
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'; 
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';
export const READ_NOTES_INDEX_REQUEST = 'GET_NOTES_INDEX_REQUEST';
export const READ_NOTES_INDEX_SUCCESS = 'GET_NOTES_INDEX_SUCCESS';
export const READ_NOTES_INDEX_FAILURE = 'GET_NOTES_INDEX_FAILURE'; 

